# 图像相关配置
image_size_height: 64  # 图像高度，单位为像素
image_size_width: 64   # 图像宽度，单位为像素

# 训练相关配置
train_batch_size: 32   # 训练批次大小
eval_batch_size: 16    # 评估批次大小
num_epochs: 10         # 训练轮数
gradient_accumulation_steps: 1  # 梯度累积步数
learning_rate: 0.0001    # 学习率
lr_warmup_steps: 500   # 学习率预热步数
save_image_epochs: 5   # 每5个epoch保存一次图像
save_model_epochs: 5   # 每5个epoch保存一次模型
mixed_precision: 'bf16'  # 使用混合精度训练，精度为bf16

# 输出和存储相关配置
output_dir: 'mcskin_diffuser'  # 输出目录
push_to_hub: False             # 不将模型推送到Hub
hub_private_repo: False        # Hub仓库为公开仓库
overwrite_output_dir: True     # 覆盖输出目录

# 其他配置
seed: 0                        # 随机种子
num_train_timesteps: 1000      # 训练时间步数
