image_size_height: 32
image_size_width: 64
train_batch_size: 32
eval_batch_size: 16
num_epochs: 10
gradient_accumulation_steps: 1
learning_rate: 1e-4
lr_warmup_steps: 500
save_image_epochs: 5
save_model_epochs: 5
mixed_precision: 'fp16'
output_dir: 'mcskin_diffuser'
push_to_hub: False
hub_private_repo: False
overwrite_output_dir: True
seed: 0
